" pkg : vim
" version : 8.0
" help :
" - :help options
" - :options
" filename : .vimrc

set nocompatible

colorscheme industry

" Command-line status 
set showmode
set showcmd
set ruler

" Left side
set number
set relativenumber
set numberwidth=4

" Windows
set splitbelow
set splitright

" Files
filetype on
syntax on

" Command-line
set wildmenu " Enables visual autocomplete

" Drawing
set lazyredraw

" Search
set wrapscan
set hlsearch
set redrawtime=1000
" cf _hlmap_
set magic

" Tab and Indent
set autoindent " Copies last line's indent
set noexpandtab
" for expandtab
set smarttab
set tabstop=4
set shiftwidth=4

" Line max length
"set textwidth=80
"set colorcolumn=+1
set colorcolumn=81

" Operations behaviour
set nostartofline " Movements go to the first column and not first character
set nojoinspaces " J adds only one space after punctuation
set tildeop
" cf _tilderemap_

" Keyboard
map Y y$
" _hlmap_
noremap Q <Nop>
nnoremap <silent> Q <Esc>:noh<CR>
" _tilderemap_
nnoremap ~~ ~l
nnoremap ~` ~~
nnoremap <C-J> gj
nnoremap <C-H> gk

inoremap jkj <Esc>

set backspace=indent,start
