set nocompatible

set ruler
set showcmd
set modeline

set number
set relativenumber

syntax on
set hlsearch

set autoindent
set noexpandtab
set smarttab
set tabstop=4
set shiftwidth=4

noremap Q <Nop>

