" pkg : vim
" help :
"   - :help options
"   - :options
" filename : ~/.vim/vimrc
" notes :
"   - viminfo location is ~/.vim/viminfo
"   - noexpandtab
"   - :To[ggleNumbers]
"   - Q :noh[lsearch]
"   - ~~ switch character case
"   - ~` switch line case
"   - <C-J> gj
"   - <C-H> gk
"   - i_jkj <Esc>

set nocompatible
set encoding=utf-8
set viminfo='100,<100,s10,n$HOME/.vim/viminfo
" ' file with marks
" < register lines
" s register size in kB
" n filename
" ---
colorscheme industry

" Command-line status 
set showmode
set showcmd
set ruler

" Left side
set number
set relativenumber
set numberwidth=4
" cf _togglenumbers_

" Windows
set splitbelow
set splitright

" Files
filetype on
syntax on

" Command-line
set wildmenu " Enables visual autocomplete

" Commands
" _togglenumbers_
function ToggleNumbers()
	if &number || &relativenumber
		set nonumber
		set norelativenumber
	else
		set number
		set relativenumber
	endif
endfunction
command ToggleNumbers call ToggleNumbers()

" Drawing
set lazyredraw

" Text Display
set listchars=tab:» ,trail:·,eol:↵,extends:},precedes:{,nbsp:%

" Search
set wrapscan
set hlsearch
set redrawtime=1000
" cf _hlmap_
set magic

" Tab and Indent
set autoindent " Copies last line's indent
set noexpandtab
" for expandtab
set smarttab
set tabstop=4
set shiftwidth=4

" Line max length
"set textwidth=80
"set colorcolumn=+1
set colorcolumn=81

" Operations behaviour
set nostartofline " Movements go to the first column and not first character
set nojoinspaces " J adds only one space after punctuation
set tildeop
" cf _tilderemap_

" Keyboard
map Y y$
" _hlmap_
noremap Q <Nop>
nnoremap <silent> Q <Esc>:noh<CR>
" _tilderemap_
nnoremap ~~ ~l
nnoremap ~` ~~
nnoremap <C-J> gj
nnoremap <C-H> gk

inoremap jkj <Esc>

" Keep selection when indenting
vnoremap < <gv
vnoremap > >gv

set backspace=indent,start
